# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React app to Azure Web App - noobmaster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up the Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Zip the build folder for deployment
      - name: Zip artifact for deployment
        run: zip -r build.zip build

      # Upload the build folder as an artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the build artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app

      # Unzip the build artifact
      - name: Unzip artifact for deployment
        run: unzip build.zip

      # Deploy the build folder to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'noobmaster'
          slot-name: 'Production'
          package: ./build
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B72718E01D65474C801F39C88FFD10AA }}
