name: Build and deploy React app to Azure Web App - noobmaster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build the app
        run: |
          npm install
          npm run build

      # Debugging step: Check if the build folder exists
      - name: Check build folder
        run: ls -l build || echo "Build folder does not exist!"

      # Updated zip command with debugging
      - name: Zip build folder for deployment
        run: |
          if [ -d "build" ]; then
            zip -r build.zip build/
          else
            echo "Build folder is missing! Ensure 'npm run build' was successful."
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Unzip build folder
        run: unzip build.zip
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'noobmaster'
          slot-name: 'Production'
          package: build/
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DD5EF150765B43C1A48EA80253A0A923 }}
